Miovision alt aggregation
CityofToronto/bdit_data-sources pull request #1024
Opened 2024-07-24 21:04 UTC by gabrielwol

## What this pull request accomplishes:

1. Remove `miovision_api.volumes_15min` (table) in place of a view. Reduces duplicate storage and complexity in aggregation. 
2. Add all movements to `miovision_api.volumes_15min_mvt_unfiltered` instead of just common `intersection_movements`. Reduces effort when  aggregating. **Do we need to do this with new trigger??**
3. Add a trigger to help with adding new movements to intersection_movements: aggregate and pad. 

## Issue(s) this solves:

- #

## What, in particular, needs to reviewed:

- 

## What needs to be done by a sysadmin after this PR is merged

_E.g.: these tables need to be migrated/created in the production schema._

2024-07-26 18:24 UTC, gabrielwol commented
Testing the new ATR view for speed: 
```sql
--test: 0.2 s with primary key
SELECT *
FROM miovision_api.volumes_15min_atr_filtered
WHERE
    intersection_uid = 6
    AND classification_uid = 1
    AND datetime_bin = '2024-06-25 12:00:00'
    AND leg <> LEFT(dir, 1);

--DR i0627 test using new view
--41s for original, 1:06 for view (1.3M rows)
SELECT
    volumes.intersection_uid,
    date_trunc('hour', volumes.datetime_bin) AS datetime_bin,
    volumes.leg,
    volumes.dir,
    classifications.classification,
    SUM(volumes.volume) AS volume
FROM miovision_api.volumes_15min_atr_filtered AS volumes
INNER JOIN miovision_api.classifications USING (classification_uid)
WHERE
    volumes.classification_uid NOT IN (2, 7)
    AND volumes.datetime_bin >= '2024-01-01'
    AND volumes.datetime_bin < '2024-05-22'
    AND volumes.intersection_uid IN (76, 88, 81, 85, 84, 87, 75, 83, 86, 49, 80, 36)
GROUP BY
    volumes.intersection_uid,
    classifications.classification,
    date_trunc('hour', volumes.datetime_bin),
    volumes.leg,
    volumes.dir;
```

2025-02-18 17:27 UTC, radumas commented
> Ok to anti join instead of set unacceptable_gaps to null in filtered view?

We tested some aggregate functions with NULLs and they silently succeed while not considering the NULL values. There could be some benefit to graphing or if someone is looking at the VIEW output without aggregating to see the ranges of dates that are unacceptable. OTOH, I think analysts should be looking at the AR table as a starting point to their analysis.

2025-02-18 21:52 UTC, radumas requested changes
Some additional requested changes to make sure the documentation is in sync with the state of the code:

- [ ] https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/getting_started.md#where-should-i-look-for-data needs to be updated
- [ ] https://github.com/CityofToronto/bdit_data-sources/tree/master/volumes/miovision#where-can-i-access-the-data should include a link to Getting Started as a better starting location for accessing the data
- [ ] The changes requested in `miovision/sql/readme.md`

2025-02-18 21:52 UTC, radumas commented on volumes/miovision/sql/readme.md
- [ ] The ERD at the top needs to be updated or deleted. Might have to ask @scann0n where the file is that created it. Or recreate in Mermaid
https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/sql/readme.md#miovision-data-relationships-at-a-glance
- [ ] The data dictionary for movement_map needs to be updated https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/sql/readme.md#movement_map
- [ ] Delete the row pertaining to `aggregate_15_min()` in the https://github.com/CityofToronto/bdit_data-sources/blob/master/volumes/miovision/sql/readme.md#aggregation-functions and **Clear Functions**
- [ ] Links are broken to the aggregate tables
       https://github.com/CityofToronto/bdit_data-sources/pull/1024/files#diff-2a53b055e4f243c0233aa9982681d3e4bdf35999ff11341b75128935af16ad84R62-R64

2025-02-26 20:41 UTC, gabrielwol commented on volumes/miovision/sql/function/function-add_intersection_movement_padding_values.sql
> +        im.classification_uid IN (1,2,6,10)
New issue: #1152

2025-02-26 21:58 UTC, gabrielwol commented
@radumas Ready for re-review. 

Since last week:
- Requested readme changes
- removed `report_dates` (we never used this, + it was an aggregation on top of removed volumes_15min table) + related functions and DAG task. 
- remove section used for testing
- replaced `movement_map` with `movement_map_new`. Switched from a query of old table to an insert. 
- Removed `volumes_mvt_atr_xover` (this table has an estimated 945M rows 😵, no longer necessary)

2025-03-14 20:42 UTC, radumas commented on volumes/miovision/sql/table/create-table-movement_map_new.sql
Could this table replace directly `movement_map`? Adding `_new` as a suffix is inviting trouble by needing to update an object again.

2025-03-14 20:45 UTC, radumas commented
> @radumas Ready for re-review.
> 
> Since last week:
> 
>     * Requested readme changes
> 
>     * removed `report_dates` (we never used this, + it was an aggregation on top of removed volumes_15min table) + related functions and DAG task.
> 
>     * remove section used for testing
> 
>     * replaced `movement_map` with `movement_map_new`. Switched from a query of old table to an insert.
> 
>     * Removed `volumes_mvt_atr_xover` (this table has an estimated 945M rows 😵, no longer necessary)
> 
>     * Smol fluff: 'plpgsql' to plpgsql x 6

All these changes are great. My only remaining quibble is with the `_new` suffix.

2025-03-17 17:58 UTC, gabrielwol commented on volumes/miovision/sql/table/create-table-movement_map_new.sql
@radumas I renamed the table, and removed bike approach & ped exits from this table. Before they were implicitly being excluded as duplicates in a UNION step, now they are explicitly excluded from ATR aggregation.

2025-03-18 18:41 UTC, radumas approved these changes
Heck yeah! Looks great. Don't forget to fluff the NULLs

2025-03-18 21:11 UTC, gabrielwol commented
SQL Changes to make:
- [ ] volumes/miovision/sql/function/function-add_intersection_movement_padding_values.sql
- [ ] volumes/miovision/sql/function/function-aggregate-volumes_15min.sql
- [ ] volumes/miovision/sql/function/function-aggregate-volumes_15min_mvt.sql
- [ ] volumes/miovision/sql/function/function-clear-report_dates.sql
- [ ] volumes/miovision/sql/function/function-clear-volumes_15min.sql
- [ ] volumes/miovision/sql/function/function-clear-volumes_15min_mvt.sql
- [ ] volumes/miovision/sql/function/function-create_mm_nested_volumes_partitions.sql
- [ ] volumes/miovision/sql/function/function-create_yyyy_volumes_15min_partition.sql
- [ ] volumes/miovision/sql/function/function-get_report_dates.sql
- [ ] volumes/miovision/sql/function/function-identify-zero-counts.sql
- [ ] volumes/miovision/sql/table/create-table-intersection_movements.sql
- [ ] volumes/miovision/sql/table/create-table-movement_map.sql
- [ ] volumes/miovision/sql/table/create-table-movement_map_new.sql
- [ ] volumes/miovision/sql/table/create-table-report_dates.sql
- [ ] volumes/miovision/sql/table/create-table-volumes_15min.sql
- [ ] .../table/create-table-volumes_15min_mvt.sql → ...te-table-volumes_15min_mvt_unfiltered.sql
- [ ] volumes/miovision/sql/table/create-table-volumes_tmc_atr_xover.sql
- [ ] volumes/miovision/sql/updates/update-mio_volumes15min_partitioning.sql
- [ ] volumes/miovision/sql/views/create-view-volumes_15min_atr_filtered.sql
- [ ] volumes/miovision/sql/views/create-view-volumes_15min_filtered.sql
- [ ] volumes/miovision/sql/views/create-view-volumes_15min_mvt_filtered.sql
- [ ] volumes/miovision/sql/views/create-view-volumes_15min_tmc.sql

2025-03-19 15:54 UTC, gabrielwol commented
New rows added to intersection_movements now automatically update volumes_15min_mvt_unfiltered using a trigger 🎉 

```
NOTICE:  Wed Mar 19 15:52:27.551079 2025 UTC Done adding to 15min MVT bin based on intersection_movement new rows. 1924 rows added.
INSERT 0 1

Query returned successfully in 5 secs 862 msec.
```

2025-03-19 18:00 UTC, gabrielwol commented
to do: 
- [ ] insert data during `unacceptable_gaps` into `volumes_15min_mvt_unfiltered` to match new aggregation method

2025-03-21 16:21 UTC, merged

2025-09-19 20:21 UTC, gabrielwol commented
> to do:
> 
>     * [x]  insert data during `unacceptable_gaps` into `volumes_15min_mvt_unfiltered` to match new aggregation method
> 
> 
> This was accomplished by simply setting all the nulls to 0 in `volumes_15min_mvt_unfiltered`, since the previous method was to left join unacceptable gaps and set those (padded, zero) volumes to null.

This was incorrect, since the gaps don't have to cover the whole 15 minute period. Wael discovered this error as he was investigating data gaps in Miovision.

Implemented this fix today, (still) running year by year:

```sql
--2019
--UPDATE 150893
--Query returned successfully in 56 secs 272 msec.

--2020
--UPDATE 213973
--Query returned successfully in 1 min 49 secs.

--2021
--UPDATE 136461
--Query returned successfully in 6 min 19 secs.

--2022
--UPDATE 125247
--Query returned successfully in 12 min 22 secs.


WITH v15_gaps AS (
    SELECT datetime_bin_15(datetime_bin) AS datetime_bin, leg, classification_uid, intersection_uid, movement_uid, SUM(volume) AS volume_15min
    FROM miovision_api.volumes
    WHERE
        volume_15min_mvt_uid IS NULL AND datetime_bin >= '2023-01-01' AND datetime_bin < '2024-01-01'
    GROUP BY 1,2,3,4,5
),

updated AS (
    UPDATE miovision_api.volumes_15min_mvt_unfiltered AS v15
    SET volume = v15_gaps.volume_15min
    FROM v15_gaps
    WHERE
        v15.datetime_bin = v15_gaps.datetime_bin
        AND v15.leg = v15_gaps.leg
        AND v15.classification_uid = v15_gaps.classification_uid
        AND v15.intersection_uid = v15_gaps.intersection_uid
        AND v15.movement_uid = v15_gaps.movement_uid
    RETURNING v15.volume_15min_mvt_uid, v15.intersection_uid, v15.datetime_bin, v15.classification_uid, v15.leg, v15.movement_uid
)

UPDATE miovision_api.volumes AS v
SET volume_15min_mvt_uid = v15.volume_15min_mvt_uid
FROM updated AS v15
WHERE v.volume_15min_mvt_uid IS NULL
    AND v.datetime_bin >= '2023-01-01'
    AND v.datetime_bin < '2024-01-01'
    AND v.datetime_bin >= v15.datetime_bin
    AND v.datetime_bin < v15.datetime_bin + interval '15 minutes'
    AND v15.leg = v.leg
    AND v15.classification_uid = v.classification_uid
    AND v15.intersection_uid = v.intersection_uid
    AND v15.movement_uid = v.movement_uid
```