RODARS pipeline
CityofToronto/bdit_data-sources pull request #1103
Opened 2024-11-29 17:53 UTC by gabrielwol

## What this pull request accomplishes:

- 
- 

## Issue(s) this solves:

- #

## What, in particular, needs to reviewed:

- 

## What needs to be done by a sysadmin after this PR is merged

_E.g.: these tables need to be migrated/created in the production schema._

2025-01-10 21:55 UTC, gabrielwol commented
Ready to review! Will add some more usage examples to readme at some point.

2025-02-07 22:04 UTC, radumas requested changes
Commenting on the documentation.

Pleased that the docs are extensive, you have thought out the limitations of the data, done some exploratory analysis and the use of the callouts for extra punchy information. 

I have some thoughts on re-ordering the README, but maybe we merge this and solicit feedback from users.

I have added some small editorial comments on language.

I think the big thing missing in terms of documentation is that parent folders should have a brief description of the contents of this folder so that people can know where to find it.

Also should this folder be more accurately called something like `lane_obstructions`? Or `road_permits`? Since the data are for events *and* construction (right?)

2025-02-10 16:01 UTC, chmnata commented on events/construction/sql/create-table-itsc_factors_lanesaffectedpattern.sql
> +GRANT SELECT ON TABLE itsc_factors.lanesaffectedpattern TO bdit_humans WITH GRANT OPTION;
without grant option

2025-02-10 16:01 UTC, chmnata commented on events/construction/sql/create-function-get_lanesaffected_sum.sql
> +GRANT EXECUTE ON FUNCTION itsc_factors.get_lanesaffected_sums(text) TO public;
bdit human instead of public?

2025-02-10 16:06 UTC, chmnata commented on events/construction/sql/create-view-rodars_locations.sql
> +        --find geoms for centreline that do not appear in centreline_latest
ohhhh nice

2025-02-10 16:06 UTC, chmnata commented on events/construction/sql/insert-rodars_issue_locations.sql
> +--ON CONFLICT (divisionid, issueid, locationindex, direction)
delete if not needed anymore?

2025-02-11 17:28 UTC, gabrielwol commented
@radumas readme changes ready for re-review:
- renamed folder to road_permits, moved existing contents of events into events/special_events and added events level readme. 
- updated reference in top level data-sources readme + removed old `road_closure` folder

2025-02-13 21:26 UTC, radumas approved these changes
Looks great! Thank you!

2025-02-14 14:25 UTC, gabrielwol commented
> Is there a bug in the linting action that it isn't annotating?

I also noticed previously on this PR there were some lines being erroneously annotated with line length sqlfluff error. Perhaps time to look into upgrading sqlfluff action.

2025-02-14 14:25 UTC, merged