Rescu
CityofToronto/bdit_data-sources pull request #297
Opened 2020-04-22 18:13 UTC by jovenc

## What this pull request accomplishes:
- Script to read files and insert data into postgresql table
- Deploy the script on terminal server and schedule it to run daily
- Airflow the daily process of checking if the process is running and if the counts make sense
- Added a short description about RESCU in the root README 

## Issue(s) this solves:

- #291 
- #296 

## What, in particular, needs to reviewed:

- The rescu folder and root README

2020-09-06 22:41 UTC, radumas requested changes
My bad. I should've stated that `rescu` is a subset of `volume/` data. 

The `rescu` folder needs a README, which should include details on how the python script is run, why there's a dag to check that the data is ok. 

I need to also check that I've committed the changes I made to make it run on the terminal server 😬

2020-09-06 22:41 UTC, radumas commented on README.md
> +## RESCU - Traffic Camera
I am reasonably certain the volumes come from loop detectors

2020-09-06 22:41 UTC, radumas commented on dags/check_rescu.py
> +        http_conn_id='slack',
Now seems like a good time to request using the new style of Slack message (see documentation). The people to tag are myself, Charles, and Aakash.

2020-09-10 21:03 UTC, jovenc commented
RESCU PR comments addressed

2020-09-11 13:45 UTC, radumas commented on rescu/README.md
> +```sql
`sql` code block but the code is actually Python.

2020-09-11 14:47 UTC, radumas approved these changes

2020-09-11 14:48 UTC, merged