Bulk postprocessing script and CSV data infrastructure
CityofToronto/bdit_data-sources pull request #366
Opened 2020-11-30 17:34 UTC by cczhu

## What this pull request accomplishes:

- Adds `miov_bulk_postprocessor.py`, a script that performs only the gap-finding and 15-minute aggregation steps of `intersection_tmc.py` on either CSV or API data.
- Adds functions and tables to handle the recent CSV data dumps.
- Adds development notebooks that generated plots and analyses in #331 and #341.

## Issue(s) this solves:

- #331 
- #341 

## What, in particular, needs to reviewed:

- Scan of `miov_bulk_postprocessor.py` for blatant errors.
- Check that all the Readme updates are sensible.
- I don't think there's a huge need to check the Jupyter Notebooks, since they weren't really used to develop any in-production code.

2021-01-25 21:43 UTC, radumas requested changes
Looks good besides the one CodeFactor issue raised.

I also feel like postgresql should do implicit conversion of a `'YYYY-MM-DD'` string to a date but... not the end of the world

2021-01-25 21:43 UTC, radumas commented on volumes/miovision/api/csv_scripts/miov_bulk_postprocessor.py
> +import sys
CodeFactor doesn't like that you import sys twice

2021-01-26 18:09 UTC, cczhu commented
Everything should be good to merge now. I'll do a check of whether the API and CSV aggregation functions are identical after merging (since it would require updating the API scripts and so should be a separate PR).

2021-01-28 20:49 UTC, merged

2021-01-28 20:50 UTC, radumas commented
Are those the bulk processing ones or the main pipelines ones?

2021-01-28 20:51 UTC, cczhu commented
I think there may be some change made to the bulk processing SQL queries that we want to port over to the main pipeline, but I'll have to double-check. If I discover anything I'll make a PR.

To be clear, I don't think anything breaks once `master` is pushed to production.