Remove former team membership from ownership
CityofToronto/bdit_data-sources pull request #384
Opened 2021-02-15 14:40 UTC by cczhu

## What this pull request accomplishes:

- Removes Rick, Joven and myself from `miovision_api`/`miovision_csv` table ownership. 😩

## Issue(s) this solves:

- 😩

## What, in particular, needs to reviewed:

- Need admin help to switch ownership of all elements of `miovision_api` and `miovision_csv` schemas to `miovision_admins`.
- Charles to put #380 into production once that's finished (currently Joven owns a table that need to be changed).
- We should consider making it a rule that any permanent table generated outside of one's personal schema must be owned by an admin group. (I suppose that means I'll need to create `collisions_admins` and `vz_admins` groups. For the next purge we should change all schema element ownership in `vz_analysis`, `vz_challenge`, `vz_safety_programs`, etc. to group ownership.

2021-03-10 02:36 UTC, aharpalaniTO requested changes

2021-03-10 02:36 UTC, aharpalaniTO commented on volumes/miovision/sql/csv_data/create-view-report_volumes_15min.sql
>  ALTER TABLE miovision.report_volumes_15min
this should be `miovision_csv.report_volumes_15min`

2021-03-10 02:36 UTC, aharpalaniTO commented
I changed all the permissions via the admin account. One change requested and then I'll merge.

2021-03-12 02:14 UTC, aharpalaniTO approved these changes

2021-03-12 02:14 UTC, merged

2021-05-10 20:28 UTC, cczhu commented
Okay done.