VZ Map: add 2021 SSZ Google Sheet to airflow process
CityofToronto/bdit_data-sources pull request #394
Opened 2021-04-20 16:11 UTC by KatiRG

## What this pull request accomplishes:

- updates script `bdit_data-sources/vision_zero/schools.py` to read from 2021 Google sheet
- updates dag `bdit_data-sources/dags/vz_google_sheets.py` with `task4` that calls `pull_from_sheet` for 2021

## Issue(s) this solves:
#392 

## What, in particular, needs to reviewed:

- You can have a look at the added code but the real check would be to run the dag

2021-04-22 14:45 UTC, radumas requested changes
No issues with the code itself. I take it you actually tested pulling the 2021 sheet in isolation?

2021-04-22 14:47 UTC, radumas commented
Oh I guess CodeFactor doesn't like that the file doesn't end with an empty newline.

2021-04-22 15:15 UTC, KatiRG commented
> 
> 
> No issues with the code itself. I take it you actually tested pulling the 2021 sheet in isolation?

Yes 👍

2021-04-22 15:19 UTC, KatiRG commented on vision_zero/schools.py
>  """ This script reads 3 Vision Zero google spreadsheets ('2018 School Safety Zone', '2019 School Safety Zone',
done

2021-04-22 15:41 UTC, KatiRG commented on vision_zero/README.md
done (according to the current method)

2021-04-22 16:10 UTC, KatiRG commented on vision_zero/create-table-school_safety_zone_2021_raw.sql
> +CREATE TABLE vz_safety_programs_staging.school_safety_zone_2021_raw
Do you mean the view that selects from all these tables would not need separate CTEs? This is the skeleton of what we have now:
```
WITH staging2018 AS (
	SELECT *
	FROM vz_safety_programs_staging.school_safety_zone_2018_raw a
	WHERE locations_zone IS NOT NULL
)
, staging2019 AS (
	SELECT *
	FROM vz_safety_programs_staging.school_safety_zone_2019_raw b
	WHERE locations_zone IS NOT NULL
)
, staging2020 AS (
	SELECT *
	FROM vz_safety_programs_staging.school_safety_zone_2020_raw c
	WHERE locations_zone IS NOT NULL
)
, staging2021 AS (
	SELECT *
	WHERE locations_zone IS NOT NULL
)
```

2021-04-26 14:57 UTC, radumas requested changes
Are you going to consolidate these three dags? They don't all need to be merged to main.

Also the config **should not** be committed to GitHub

2021-04-26 16:42 UTC, KatiRG commented
> 
> 
> Are you going to consolidate these three dags? They don't all need to be merged to main.
There should only be one dag  now, `vz_google_sheets.py`. I removed the test dag `vz_google_sheets_var.py`.
> 
> Also the config **should not** be committed to GitHub
ah yes! it's deleted now

2021-04-26 18:50 UTC, KatiRG commented on vision_zero/create-table-school_safety_zone_2021_raw.sql
> +CREATE TABLE vz_safety_programs_staging.school_safety_zone_2021_raw
ok got it! I made a parent table now and defined each year table as a child

2021-04-26 21:38 UTC, radumas requested changes
One comment on the sql. Otherwise looks good. Great instructions.

2021-04-27 12:31 UTC, KatiRG commented on vision_zero/create-table-school_safety_zone_2021_raw.sql
> +CREATE TABLE vz_safety_programs_staging.school_safety_zone_raw_parent (
Makes sense. The file now has just the query for creating the 2021 staging table. I moved the query to define the parent table into the vz programs repo.

2021-04-27 20:14 UTC, radumas requested changes
I didn't realize there wasn't any sql stored in this folder. which begs the question, why include only the 2021 SSZ creation query in this PR, seems extraneous if it's defined elsewhere

2021-04-28 12:05 UTC, KatiRG commented
> 
> 
> I didn't realize there wasn't any sql stored in this folder. which begs the question, why include only the 2021 SSZ creation query in this PR, seems extraneous if it's defined elsewhere

True that the parent query is elsewhere. But if you need to add a new spreadsheet you need to follow the steps in this repo so I thought it was better to avoid having to hop over to another repo just to get started (making the empty table is really the first thing you have to do).

The query to make the new table is written in the [README](https://github.com/CityofToronto/bdit_data-sources/tree/ssz2021/vision_zero#31-create-empty-table-in-database-to-store-spreadsheet) of this repo so if you think this is sufficient then I can delete the actual sql file `create-table-school_safety_zone_2021_raw.sql`.

2021-04-28 13:11 UTC, radumas commented
Yeah I think the steps in the README are clear enough so the file is unnecessary. Thanks.

2021-04-28 19:58 UTC, radumas approved these changes

2021-04-28 19:59 UTC, merged