Add here aggregation steps
CityofToronto/bdit_data-sources pull request #445
Opened 2022-02-08 16:12 UTC by chmnata

2022-02-11 19:00 UTC, radumas requested changes
Great work putting this together. Some minor formatting fixes.

Did you fix the bug in the aggregation sql snippets I highlighted during your talk?

2022-02-11 19:00 UTC, radumas commented on here/here_aggregation.md
> +## What is HERE data?
What is HERE data should be merged into the `here/readme.md` and this aggregation readme should be referenced from it.

2022-02-11 19:00 UTC, radumas commented on here/here_aggregation.md
> +    - [Using congestion tables](#using-congetion-tables)
Typo in the link

2022-02-11 19:00 UTC, radumas commented on here/here_aggregation.md
> +## Geometry
These headings should be H3

2022-02-12 00:02 UTC, radumas requested changes
Some smol further changes required

2022-02-12 00:02 UTC, radumas commented on here/here_aggregation.md
> +GROUP BY    corridor_id, analysis_period, time_period, week, tt_baseline
I think trying to sum `tt_baseline` while grouping by it doesn't make sense.

2022-02-14 17:15 UTC, radumas requested changes
sorry, some final nitpicking.

2022-02-14 17:15 UTC, radumas commented on here/here_aggregation.md
> +	SELECT 		input_table.uid,
In the step above this is `corridor_id`

2022-02-14 17:15 UTC, radumas commented on here/here_aggregation.md
> +	SELECT 		b.uid,
there's no table here aliased as `b`

2022-02-14 17:15 UTC, radumas commented on here/here_aggregation.md
> +	SELECT 		input_table.uid,
`uid` then gets used in the rest of the steps

2022-02-15 15:24 UTC, chmnata commented
re-re-re-re-review requested @radumas :meow_salute:

2022-02-15 23:08 UTC, radumas approved these changes
grrrrrrrreat 🐯

2022-02-15 23:08 UTC, merged