Mio doc updates
CityofToronto/bdit_data-sources pull request #446
Opened 2022-02-09 23:17 UTC by scann0n

## What this pull request accomplishes:

- Edits to volumes/miovision/readme.md to incorporate bicycle approaches
- Other bonus features like an ERD, updated mio-map, more table descriptions, less outdated info and more!!!

## Issue(s) this solves:

- #423

## What, in particular, needs to reviewed:

- Are things explained correctly? Should anything else be added?

2022-02-16 17:19 UTC, radumas reviewed
Mildly annoying that I can't comment on past work.
A borked link snuck into the TOC

https://github.com/CityofToronto/bdit_data-sources/blob/f72ab2a30a60ea90897dae41a2d9dbd9a00ac440/volumes/miovision/README.md?plain=1#L20

This should actually be `volumes_15min_mvt`

2022-02-17 16:00 UTC, tahaislam commented
I got it from the documentation that all tables and views are in miovision_api schema. But it wasn't clear in the first paragraph. And as there are two other miovision schemas in BigData DB (miovision_csv & miovision_new). Are they relevant to miovision?
How did you draw this ERD? Is there an automatic way to generate it? I'm interested in learning that
Why NULLing the whole hour if only a single 15-min interval is NULL? Is there a reason or for easier/feasible implementation?
Why does unacceptable_gaps have a field "accept"? does it contain all gaps or just unaccepted ones?

2022-02-22 20:18 UTC, radumas commented
Solid questions Islam!

> I got it from the documentation that all tables and views are in miovision_api schema. But this wasn't clear in the first paragraph. And as there are two other miovision schemas in BigData DB (miovision_csv & miovision_new). Are they relevant to miovision? 

`miovision_new`: was created for testing something and should be dealt with in a subsequent purge.
`miovision_csv`: I need to look into this more (upcoming purge) but this definitely contains the same data as the `api` schema for a particular period of time because the API data was unreliable so we got a huge dump of data from Miovision via csv. That is definitely duplicated across the schema and needs to be purged. For the King Street pilot we were also getting csv data before the API was up and running. I forget what span of time those cover and I'm not 100% sure where it is.


> How did you draw this ERD? Is there an automatic way to generate it? 

I think this is what Sarah was griping about in pgAdmin.

>I'm interested in learning that Why NULLing the whole hour if only a single 15-min interval is NULL? Is there a reason or for easier/feasible implementation?

The idea was that a typical workflow with the data is summing the data by hour before averaging or aggregating further, so wanted to ensure that low hourly volumes didn't accidentally get generated without someone checking the unacceptable gaps table. 

> Why does unacceptable_gaps have a field "accept"? does it contain all gaps or just unaccepted ones?

I'm going to hypothesize that, in order to validate the process, any gap is identified in the table, and then based on the dynamic volume algorithm it is labelled as acceptable (due to natural low volume) or unacceptable (the camera probably didn't record data).

2022-02-22 20:27 UTC, scann0n commented
My two cents in blue below…

From: Raphael Dumas ***@***.***
Sent: February 22, 2022 3:18 PM
To: CityofToronto/bdit_data-sources ***@***.***>
Cc: Sarah Cannon ***@***.***>; Author ***@***.***>
Subject: Re: [CityofToronto/bdit_data-sources] Mio doc updates (PR #446)


Solid questions Islam!

I got it from the documentation that all tables and views are in miovision_api schema. But this wasn't clear in the first paragraph. And as there are two other miovision schemas in BigData DB (miovision_csv & miovision_new). Are they relevant to miovision?

miovision_new: was created for testing something and should be dealt with in a subsequent purge.
miovision_csv: I need to look into this more (upcoming purge) but this definitely contains the same data as the api schema for a particular period of time because the API data was unreliable so we got a huge dump of data from Miovision via csv. That is definitely duplicated across the schema and needs to be purged. For the King Street pilot we were also getting csv data before the API was up and running. I forget what span of time those cover and I'm not 100% sure where it is.

I'll make it more clear that miovision_api is the schema we've all be waiting for…

How did you draw this ERD? Is there an automatic way to generate it?

I think this is what Sarah was griping about in pgAdmin. Absolutely I will take the opportunity to gripe a little more…it was painstakingly created in pgAdmin then "coloured in" using good ole' PowerPoint!

I'm interested in learning that Why NULLing the whole hour if only a single 15-min interval is NULL? Is there a reason or for easier/feasible implementation?

The idea was that a typical workflow with the data is summing the data by hour before averaging or aggregating further, so wanted to ensure that low hourly volumes didn't accidentally get generated without someone checking the unacceptable gaps table.

Why does unacceptable_gaps have a field "accept"? does it contain all gaps or just unaccepted ones?

I'm going to hypothesize that, in order to validate the process, any gap is identified in the table, and then based on the dynamic volume algorithm it is labelled as acceptable (due to natural low volume) or unacceptable (the camera probably didn't record data). Yeah there's even some filtering then joining that happens on this field – so if accept = FALSE the data from that hour doesn't end up in the volume_15min_mvt or volume_15min tables.

—
Reply to this email directly, view it on GitHub<https://github.com/CityofToronto/bdit_data-sources/pull/446#issuecomment-1048176894>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWT2MNTSRGK45QOFZGROIBDU4PVRFANCNFSM5N65WLGQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-02-23 22:18 UTC, tahaislam commented
Thanks, Raphael and Sarah. Re the ERD, I guess Sarah's last week lightning talk answered that

2022-03-10 20:02 UTC, radumas requested changes
Thanks for this extensive rewrite, a few smol change requests

2022-03-10 20:02 UTC, radumas commented on volumes/miovision/Archive.md
> +The data pulling script currently *does not support* deleting and re-processing data that is not in one-day blocks (for example we cannot delete and re-pull data from `'2021-05-01 16:00:00'` to `'202
I think this might still be relevant

2022-03-10 22:09 UTC, radumas commented
oh I tried adding a comment on the geojson that I think it could replace the old geojson so there aren't two geojsons.

2022-04-06 01:23 UTC, radumas approved these changes
Noice!

2022-04-06 01:24 UTC, merged