#465 Add retry to pull here DAG
CityofToronto/bdit_data-sources pull request #467
Opened 2022-06-06 14:33 UTC by chmnata

## What this pull request accomplishes:

- Add `retry` to pull_here DAG

## Issue(s) this solves:

- #465

## What, in particular, needs to reviewed:

- the two lines I changed in the DAG

2022-06-06 15:29 UTC, radumas requested changes
This looks good.

My one suggestion is to include  `retry_exponential_backoff = True`. 

> `retry_exponential_backoff` ([bool](https://docs.python.org/3/library/functions.html#bool)) -- allow progressive longer waits between retries by using exponential backoff algorithm on retry delay (delay will be converted into seconds)

My understanding is then the retries will be after 45 minutes, 90 minutes, 3 hours.

Maybe the retry delay should be something like 2 hours instead? How often do you feel it work again after retrying immediately?

2022-06-07 13:01 UTC, chmnata commented
Usually when it fails at 16:30ish, I am able to rerun it at around 17 or so, if not 17:30. How about 1 hour?

2022-06-07 13:47 UTC, radumas commented
Deal!

2022-06-07 14:18 UTC, radumas approved these changes

2022-06-07 14:36 UTC, merged