I0669 aggregate volumes 15min mvt tries to insert duplicate values
CityofToronto/bdit_data-sources pull request #674
Opened 2023-08-15 17:24 UTC by gabrielwol

## What this pull request accomplishes:
- Adds new function `miovision_api.aggregate_15_min_mvt_single_intersection` to aggregate just a single intersection into `volumes_15min_mvt`.
- Improvements to existing `miovision_api.aggregate_15_min_mvt` function

## Issue(s) this solves:
- Closes #669 

## What, in particular, needs to reviewed:
- Fluffed and unnested the CTE in base function https://github.com/CityofToronto/bdit_data-sources/blob/09130027d9b2ab637dd4876663d804467757909d/volumes/miovision/sql/function-aggregate-volumes_15min_mvt.sql

- Duplicated new base function but added an intersection function argument and added an anti join to new function to prevent adding duplicate 0 padded values. [function-aggregate-volumes_15min_mvt_single_intersection.sql](https://github.com/CityofToronto/bdit_data-sources/blob/09130027d9b2ab637dd4876663d804467757909d/volumes/miovision/sql/function-aggregate-volumes_15min_mvt_single_intersection.sql#L38-L41)
https://github.com/CityofToronto/bdit_data-sources/blob/09130027d9b2ab637dd4876663d804467757909d/volumes/miovision/sql/function-aggregate-volumes_15min_mvt_single_intersection.sql#L38-L41
`WHERE...`
https://github.com/CityofToronto/bdit_data-sources/blob/09130027d9b2ab637dd4876663d804467757909d/volumes/miovision/sql/function-aggregate-volumes_15min_mvt_single_intersection.sql#L72-L73

- Updated https://github.com/CityofToronto/bdit_data-sources/compare/master...i0669-aggregate-volumes_15min_mvt-tries-to-insert-duplicate-values to use the new single intersection function if intersections are specified in function call. 

## What needs to be done by a sysadmin after this PR is merged
- Update definition of `miovision_api.aggregate_15_min_mvt` 
- Add new function `miovision_api.aggregate_15_min_mvt_single_intersection`

2023-11-07 19:30 UTC, radumas requested changes
Great work! All the SQL looks good, just a minor issue in `cur.execute`

2023-11-07 19:30 UTC, radumas commented on volumes/miovision/api/intersection_tmc.py
> +                        cur.execute(update, time_period. c_intersec.uid)
there's a period here instead of a comma. I also think you might need to expand the `time_period` tuple and pass one large tuple of parameters.

2023-11-07 19:30 UTC, radumas commented on volumes/miovision/sql/function-aggregate-volumes_15min_mvt_single_intersection.sql
> +GRANT EXECUTE ON FUNCTION miovision_api.aggregate_15_min_mvt_single_intersection(date, date, int) TO public;
I think we could probably, actually, revoke this

2023-11-07 19:30 UTC, radumas commented on volumes/miovision/sql/function-aggregate-volumes_15min_mvt.sql
> +GRANT EXECUTE ON FUNCTION miovision_api.aggregate_15_min_mvt(date, date) TO public;
I think we should actually revoke this.

2023-11-07 20:51 UTC, gabrielwol commented on volumes/miovision/sql/function-aggregate-volumes_15min_mvt.sql
> +GRANT EXECUTE ON FUNCTION miovision_api.aggregate_15_min_mvt(date, date) TO public;
Done

2023-11-07 20:59 UTC, gabrielwol commented
Ready for re-review!

2023-11-11 22:26 UTC, radumas approved these changes

2023-11-13 14:03 UTC, merged

2023-11-13 14:08 UTC, chmnata commented
Changes applied on postgres + airflow