#615 miovision alert api
CityofToronto/bdit_data-sources pull request #722
Opened 2023-10-17 20:19 UTC by gabrielwol

## What this pull request accomplishes:
- A small new DAG to pull Miovision Alerts into the database. Will be useful for communicating issues to Miovision - we can be aware of any current alerts. 
- Backfilled for this year. 
- Updated the readmes.

## Issue(s) this solves:
- #615 

## What, in particular, needs to reviewed:
- The insert_data sql. Updating existing records during the insert to extend end_times. 

## What needs to be done by a sysadmin after this PR is merged
- Checkout these files in data_scripts.

2024-04-18 15:20 UTC, gabrielwol commented on volumes/miovision/sql/table/create-table-alerts.sql
> +    intersection_id text COLLATE pg_catalog."default" NOT NULL,
The reason I decided against adding the more usable `intersection_uid` to this table is that during my testing there were alerts for new intersections we don't have in our database yet + for this API endpoint there's no intersection param so we have to pull all the alerts. So if I add `intersection_uid` column then some will be null :(

2024-04-18 15:21 UTC, gabrielwol commented on volumes/miovision/sql/table/create-table-alerts.sql
> +Note: a more detailed description is available on Miovision One.';
oh good call!

2024-04-18 15:24 UTC, radumas commented on dags/miovision_alerts.py
> +r"""### Daily Miovision Alert Pull DAG
would we end up at a point where aggregation would depend on alert data?
I guess that would be more on the side of the views?

2024-04-18 15:30 UTC, gabrielwol commented on dags/miovision_alerts.py
> +r"""### Daily Miovision Alert Pull DAG
Requires some more investigation, but I think mostly alert == zero data.

2024-04-18 15:42 UTC, chmnata commented on volumes/miovision/sql/table/create-table-alerts.sql
> +    intersection_id text COLLATE pg_catalog."default" NOT NULL,
HMMMM I see

2024-04-18 15:44 UTC, chmnata commented on volumes/miovision/sql/table/create-table-alerts.sql
> +    intersection_id text COLLATE pg_catalog."default" NOT NULL,
I think having null is fine in that case 🤔 , we can add a step in the adding intersection doc to do an update on this table after inserting new intersection? Having intersection_uid would be very helpful

2024-04-18 15:48 UTC, chmnata commented on volumes/miovision/sql/README.md
> +
nvm, the open_issue table is a better candidate for this

2024-04-18 18:18 UTC, gabrielwol reviewed
Review changes made!

2024-04-18 18:18 UTC, gabrielwol commented on dags/miovision_alerts.py
> +r"""### Daily Miovision Alert Pull DAG
I was wrong! There are volumes during many of these alerts! We may need to use these similarly to anomalous_ranges. Will open a new issue. 

```sql
SELECT a.intersection_uid, alert, start_time, end_time, SUM(volume)
FROM miovision_api.alerts AS a
LEFT JOIN miovision_api.volumes_2024 AS v
    ON a.intersection_uid = v.intersection_uid
    AND v.datetime_bin >= a.start_time
    AND v.datetime_bin < a.end_time
WHERE a.intersection_uid IS NOT NULL
GROUP BY a.intersection_uid, alert, start_time, end_time
```

| "intersection_uid" | "alert"                  | "start_time"          | "end_time"            | "sum"   |
|--------------------|--------------------------|-----------------------|-----------------------|---------|
| 7                  | "PERIPHERAL_UNAVAILABLE" | "2024-02-14 01:05:00" | "2024-02-14 06:00:00" | 2247    |
| 24                 | "PERIPHERAL_UNAVAILABLE" | "2024-02-12 16:55:00" | "2024-02-12 17:20:00" | 1370    |
| 67                 | "TELEMETRY_UNAVAILABLE"  | "2024-01-01 00:00:00" | "2024-04-18 00:00:00" | 5936558 |
| 24                 | "PERIPHERAL_UNAVAILABLE" | "2024-02-11 02:00:00" | "2024-02-11 02:55:00" | 725     |
| 18                 | "POWER_OFF"              | "2024-04-10 02:10:00" | "2024-04-10 02:10:00" |         |
| 59                 | "PERIPHERAL_UNAVAILABLE" | "2024-03-24 01:45:00" | "2024-03-24 03:25:00" | 341     |
| 55                 | "POWER_OFF"              | "2024-03-19 14:45:00" | "2024-03-19 14:50:00" |         |
| 24                 | "PERIPHERAL_UNAVAILABLE" | "2024-02-10 01:40:00" | "2024-02-10 02:35:00" | 823     |
| 28                 | "POWER_OFF"              | "2024-03-13 10:00:00" | "2024-03-13 10:50:00" |         |
| 7                  | "IP_CONFLICT"            | "2024-02-06 13:30:00" | "2024-02-06 13:40:00" | 497     |

2024-04-18 18:18 UTC, gabrielwol commented on volumes/miovision/sql/README.md
> +end_time | timestamp | Final 5 minute interval at which the alert appeared. **Add 5 minutes to get latest possible end time.** Note this could be extended the following day. | 2024-01-21 15:35:00 |
Example added!

2024-04-18 18:29 UTC, chmnata commented on volumes/miovision/sql/table/create-table-alerts.sql
> +Note: a more detailed description is available on Miovision One.';
peffffecccgt

2024-04-18 18:39 UTC, chmnata commented on volumes/miovision/api/pull_alert.py
> +        df = pd.DataFrame(response).drop_duplicates()
got it!

2024-04-18 19:00 UTC, chmnata requested changes
One last change before merging

2024-04-19 17:55 UTC, chmnata approved these changes

2024-04-19 17:55 UTC, merged