731 document wys mobile sign process
CityofToronto/bdit_data-sources pull request #733
Opened 2023-10-30 20:08 UTC by gabrielwol

## What this pull request accomplishes:
- Updates documentation for WYS, particularly the DAG, data tables, mobile sign process. 

## Issue(s) this solves:
- #731 

## What, in particular, needs to reviewed:
- 

## What needs to be done by a sysadmin after this PR is merged
Nothing

2023-11-06 21:30 UTC, radumas requested changes
This is really great. Appreciate the linking to open issues. The merdiagrams really tie the documentation together. One minor comment.

We could move the documentation of the aggregate tables to the higher level... but maybe let's save that for when someone tries to analyze this data.

2023-11-06 21:30 UTC, radumas commented on wys/api/README.md
> +- It is not regularly updated and the script used to create it is lost.
Yikes. Good catch.

2023-11-06 21:30 UTC, radumas commented on wys/api/README.md
> +This table contains locations of stationary and mobile signs. It also contains information about each sign's API ID, direction of traffic, address, and name.
I do realize this is repeated a few times below, but still think it could be a useful caveat for anyone looking at this table metadata in particular

2023-11-13 14:49 UTC, gabrielwol commented
@radumas ready for re-review. Responded to your two comments.

2023-11-13 15:58 UTC, merged