Update getting_started.md
CityofToronto/bdit_data-sources pull request #743
Opened 2023-11-07 22:09 UTC by scann0n

Still waiting to see if the code snippet runs, and what data it should refer to...

## What this pull request accomplishes:

- updates miovision's getting started.md with a code snippet and some more discussion on approach vs exit volumes
- 

## Issue(s) this solves:

- #742

## What, in particular, needs to reviewed:

- does the code run, and should the reference to `mio_staging` be changed to `miovision_api`?

## What needs to be done by a sysadmin after this PR is merged
Nothing
_E.g.: these tables need to be migrated/created in the production schema._

2023-11-08 15:50 UTC, scann0n commented
Okay this is ready for review and I nominated @gabrielwol !!!

2023-11-09 20:43 UTC, gabrielwol commented
@scann0n I haven't had a chance to fully wrap my head around this and I have to call it quits for this afternoon.
I do have 1 main comment so far which is that there this is missing high level description of which of `volumes_15min` / `volumes_15min_mvt` to use for which purposes. There is some comparison of TMC / ATR but these acronyms don't correspond to the names of the two main aggregate tables which just makes things more confusing. Maybe we need to rename the 15min tables??? 

Having the new code example in [Calculating Volumes on a Segment](https://github.com/CityofToronto/bdit_data-sources/blob/158b5cb943da73598e59c8f45da33b5d4d397b0d/volumes/miovision/getting_started.md#calculating-volumes-on-a-segment) is nice - maybe a corresponding diagram would drive home that point even more.

2023-11-09 21:12 UTC, scann0n commented
There's a description of `volumes_15min` and `volumes_15min_mvt` in the main readme and I will certainly refer back to it... I will hold off on any edits (including the diagram, which I have and totally agree with including) until your review is complete!!!

2023-11-10 19:01 UTC, radumas commented on volumes/miovision/getting_started.md
> +	HAVING COUNT(DISTINCT datetime_bin) > 92
volume will be `NULL` for time bins that have been processed but where we determined the data to be dubious/gaps.

2023-11-10 21:58 UTC, gabrielwol commented
I think rather than the DR-like code we added from Wednesday, as a new user I would prefer a sampling of scenarios we may have to calculate: 

Confused about whether to use `volumes_15min` ("ATR" counts) or `volumes_15min_mvt` ("TMC" counts)? Here are some scenarios in which each may be useful: 
1. Do you need to know specific movements, eg. illegal thru movements on King St?
Use **`miovision_api.volumes_15min_mvt`**!
```sql
SUM(volume) 
FROM miovision_api.volumes_15min_mvt
WHERE movement_uid = 1 --1=thru movement
AND leg IN ('EB', 'WB') --entering the intersection on King
```

2. Do you want to know the total traffic passing through an intersection regardless of movement?
Use **`miovision_api.volumes_15min_mvt`**
```sql
SUM(volume) FROM miovision_api.volumes_15min_mvt
```
OR `miovision_api.volumes_15min` but be careful not to double count entrances and exits!
```sql
SUM(volume) FROM miovision_api.volumes_15min
WHERE leg <> dir --count only entrances
```
Which should equal:
```sql
SUM(volume) FROM miovision_api.volumes_15min
WHERE leg = dir --count only exits
```

3. Do you want to find a screenline? ie. King, east of Bathurst - use ATR (**`miovision_api.volumes_15min`**)!
```sql
SUM(volume) FILTER (WHERE dir = 'EB') AS 'EB volume'
SUM(volume) FILTER (WHERE dir = 'WB') AS 'WB volume'
FROM miovision_api.volumes_15min
WHERE leg = 'EB'
```

4. Any vehicle using King St? 
```sql
SUM(volume) FROM miovision_api.volumes_15min_mvt
WHERE
leg IN ('EB', 'WB') --these vehicles entered intersection on King
OR (leg IN ('SB', 'NB') AND movement_uid IN (2,3)) --Plus, vehicle entering from North or South turning left or right on to King. 
```

2023-11-17 16:20 UTC, gabrielwol requested changes
Whoops! I commented last week but did not mark it as "reviewed". 
Let me know what you think of my suggestions.

2024-01-16 14:50 UTC, gabrielwol approved these changes
Approve! These new diagrams/examples would have been so helpful when I was getting started - much simpler.

2024-02-13 16:04 UTC, merged