781 wys declarative partitioning
CityofToronto/bdit_data-sources pull request #782
Opened 2023-11-29 20:15 UTC by gabrielwol

## What this pull request accomplishes:

- 
- 

## Issue(s) this solves:
- Closes #781 

## What, in particular, needs to reviewed:
- 

## What needs to be done by a sysadmin after this PR is merged
- Check the 3 DAGs before merging.

2023-11-29 22:05 UTC, gabrielwol commented
Here's what's remaining to run for `wys.mobile_sign_installations`:

- [ ] drop the dependencies! (VIEW open_data.wys_mobile_detailed, MATERIALIZED VIEW wys.mobile_api_id)
```sql
SELECT public.deps_save_and_drop_dependencies(
    'wys' COLLATE pg_catalog."C",
    'mobile_sign_installations' COLLATE pg_catalog."C"
);
ALTER TABLE wys.mobile_sign_installations_staging RENAME TO mobile_sign_installations;
```
- [ ] drop ward tables inheretence and remove pkey (to be replaced with one containing ward_no)
```sql
DO $do$
DECLARE
	ward INTEGER;
    ward_table TEXT;
    pkey TEXT;
BEGIN
	FOR ward IN 1..25 LOOP
        ward_table := 'ward_'||ward::text;
        pkey := 'ward_'||ward::text||'_pkey';
        EXECUTE FORMAT($$
                       ALTER TABLE wys.%s NO INHERIT wys.mobile_sign_installations;
                       ALTER TABLE wys.%s DROP CONSTRAINT IF EXISTS %s;
                       $$, ward_table, ward_table, pkey);
	END LOOP;
END;
$do$ LANGUAGE plpgsql
```
- [ ] Drop existing table and replace with partitioned version. 
```sql
DROP TABLE wys.mobile_sign_installations; 
ALTER TABLE wys.mobile_sign_installations_staging RENAME TO mobile_sign_installations;
```

- [ ] Attach all the partitions!
```sql
DO $do$
DECLARE
	ward INTEGER;
BEGIN
	FOR ward IN 1..25 LOOP
        ward_table := 'ward_'||ward::text;
        EXECUTE FORMAT($$ALTER TABLE wys.mobile_sign_installations
                         ATTACH PARTITION wys.%s FOR VALUES IN (ward::integer);
                       $$, ward_table);
	END LOOP;
END;
$do$ LANGUAGE plpgsql
```

- [ ] Restore dependencies 
```sql
SELECT public.deps_restore_dependencies('wys', 'mobile_sign_installations');
```

2023-11-30 22:12 UTC, gabrielwol commented
The column order in github / bigdata must have been different because when I recreated the table with the github definition, the [insert is failing](https://trans-bdit.intra.prod-toronto.ca/airflow/dags/pull_wys/grid?dag_run_id=scheduled__2023-11-29T20%3A00%3A00%2B00%3A00&task_id=pull_wys&tab=logs). I added the column order to the insert in the latest commit, but `pull_wys.pull_wys` is going to keep failing until we merge this.

2023-12-04 18:48 UTC, tahaislam commented on dags/eoy_create_tables.py
> -
This [line](https://github.com/CityofToronto/bdit_data-sources/blob/bdb853f4fb869c15e795aa9e906cfba46bb1d6ef/dags/eoy_create_tables.py#L146) needs to be deleted as well. Also check if any of these deleted variables is used anywhere in the file.

2023-12-04 19:43 UTC, tahaislam requested changes
Good work, the code is looking simpler. I left some comments for you to fix. Then, I'll review/test the rest of the files.
Also, I think it should have been better to keep this PR only for WYS code and all other changes to the other DAGs to be included in a separate DAG to avoid any mass DAG failure and also to make it easier to get reviewed and tested. Maybe this's something to consider in future PRs

2023-12-04 19:43 UTC, tahaislam commented on dags/common_tasks.py
> +    from datetime import strptime
same as above

2023-12-04 19:43 UTC, tahaislam commented on dags/common_tasks.py
> +    from datetime import strptime
I think `strptime` is under `datetime.datetime`

2023-12-04 20:16 UTC, gabrielwol commented on dags/common_tasks.py
> +def check_jan_1st(ds=None): #check if Jan 1 to trigger partition creates.
Good idea.

2023-12-05 20:17 UTC, gabrielwol commented
There must be a difference in the definition between `mobile_sign_installations` and `ward_*` tables which is causing [this insert](https://trans-bdit.intra.prod-toronto.ca/airflow/dags/pull_wys/grid?dag_run_id=scheduled__2023-12-04T20%3A00%3A00%2B00%3A00&task_id=read_google_sheets&tab=logs) to fail now that the insert is being directed to the parent table and not the child table. Need to return to this before finalizing this PR.

2023-12-07 15:40 UTC, gabrielwol commented
All the tasks in the latest runs of [pull_wys](https://10.162.65.124/airflow/dags/pull_wys/grid) and [wys_monthly_summary](https://10.162.65.124/airflow/dags/wys_monthly_summary/grid?base_date=2023-11-02T23%3A59%3A59.999Z&dag_run_id=scheduled__2023-11-02T07%3A00%3A00%2B00%3A00&tab=graph&task_id=wys_mobile_summary) DAGs are now running successfully.

2023-12-07 20:58 UTC, tahaislam approved these changes
Great work

2023-12-07 21:06 UTC, merged