#966 add centreline_id to sites and sites_unfiltered
CityofToronto/bdit_data-sources pull request #968
Opened 2024-05-28 20:31 UTC by gabrielwol

## What this pull request accomplishes:

- adds `centreline_id` to `ecocounter.sites` and `ecocounter.sites_unfiltered`. 
- a sql script used to identify new matches

## Issue(s) this solves:

- #966 

## What, in particular, needs to reviewed:
- Decision to add centreline_id to sites and not to flows. I figured for flows it would be duplicated between the flows at a given site which would make it very difficult to visualize. 
- Should I also add cl_geom to `ecocounter.sites` view?

## What needs to be done by a sysadmin after this PR is merged
Nothing.

2024-05-28 21:17 UTC, gabrielwol commented
I'm not sure about these two locations. The rest are on arterials and are pretty straightforward.  
site_ids: 300026125, 300026120
![image](https://github.com/CityofToronto/bdit_data-sources/assets/80077912/88099962-0dc1-4740-b84f-63293d610f97)

2024-05-31 19:27 UTC, Nate-Wessel commented
> I'm not sure about these two locations. The rest are on arterials and are pretty straightforward. site_ids: 300026125, 300026120 ![image](https://private-user-images.githubusercontent.com/80077912/334577880-88099962-0dc1-4740-b84f-63293d610f97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODE5OTAsIm5iZiI6MTcxNzE4MTY5MCwicGF0aCI6Ii84MDA3NzkxMi8zMzQ1Nzc4ODAtODgwOTk5NjItMGRjMS00NzQwLWI4NGYtNjMyOTNkNjEwZjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4NTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMjliMWY2MjRjOGFjZDk1MDJiZTZmZDgzNGU0NjY3MTFiM2E3NjFhNmViOWY3ZjMzN2QzYmZjNzg5ZjIzNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t5Bu857KVCgQ5AaGmxFm8OLFnHl3OGqO37Tra6AgmqQ)

I think the site to the east here should definitely not have a centreline id. The one to the west, maybe? But probably not?

It really boils down to a question of what the centreline is meant to represent. Does it implicitly include the sidewalks and other peripheral paths associated with a street? Does it depend how far away they are from the main car lanes, or that they're facing the exact same direction? Does it matter if they're on both sides, or only on one side?

There's an eternal debate in OSM about how and when to map things as separate ways. I tend to [map bike lanes on both sides as part of the central way](https://www.openstreetmap.org/way/15818587), but it's almost always mapped as a separate way if the cycleway is a [two-lane path off on one side of the road](https://www.openstreetmap.org/way/660002977), which some of these Ecocounter locations are, not just the two above. (the way sidewalks are mapped in OSM is pure chaos, by the way)

I'd want to avoid any casual mistakes where someone using this data forgets that the Ecocounter sensors actually _only_ record what's directly above them, in the bike facilities, not the whole street. 

Maybe I'm over-thinking it?

2024-06-03 19:17 UTC, gabrielwol commented
@Nate-Wessel I set those two centreline_ids to null. As per @radumas's comment in slack, we could revisit if we add trails to gis_core.centreline. Ready for review.

2024-06-03 19:19 UTC, radumas commented
I think the one to the West could be tied to the street centreline (but primarily because the trail centreline doesn't exist 🤷🏻‍♂️ )

2024-06-03 19:37 UTC, Nate-Wessel requested changes
I think I would just suggest changing `centreline_id` to `nearest_centreline_id` or `associated_centreline_id` or something like that to make clear the the sensor isn't counting the centreline segment _per se_ bit just the specific bike facilities.

Or at least be clearer in the documentation for this field what the relation is. 

Looks good otherwise!

2024-06-05 18:58 UTC, gabrielwol commented
@Nate-Wessel I updated the documentation and the column comment to be more specific about only counting bike ROW!

2024-06-06 14:56 UTC, Nate-Wessel approved these changes

2024-06-06 14:58 UTC, merged