975 weather DAG task flow plus schedule change
CityofToronto/bdit_data-sources pull request #976
Opened 2024-06-03 17:56 UTC by gabrielwol

## What this pull request accomplishes:

- adjust start date in weather DAG
- replace pull_weather with task flowified weather_pull + adjust start and end dates
- converted extra_msg_str elements to string to prevent NoneType failure.

## Issue(s) this solves:
- #975 

## What, in particular, needs to reviewed:
- 

## What needs to be done by a sysadmin after this PR is merged
-

2024-06-03 19:47 UTC, chmnata requested changes
Can you update the new scheduled time in the readme as well? https://github.com/CityofToronto/bdit_data-sources/tree/master/weather#data-pipeline

2024-06-05 19:16 UTC, gabrielwol commented
Updated the readme and set the time to 830pm using a TimeSensor operator.

2024-06-07 14:04 UTC, gabrielwol commented
Not quite ready to merge yet, need to keep trying different start times to find when historical weather becomes available and then push the other data checks back to match.

2024-06-07 14:05 UTC, chmnata commented
https://climate.weather.gc.ca/FAQ_e.html#Q17 !!!!

2024-06-10 13:49 UTC, gabrielwol commented
I miscalculated 1000UTC, so we need to wait one more day for this to run at the correct time.
- Success: the check tasks still ran and reported unknown weather so the soft link worked as intended.  
- Fail: nulls were silently inserted into the historical weather tables (will add a sql check).

2024-06-12 15:35 UTC, chmnata commented on dags/weather_pull.py
> +        poke_interval=3600,
Looking at the log, it seems like its poking to check whether its 10:30am a few times starting when the dag is active (so 8am, 9am, and 10am). Would we need poke_interval here?

2024-06-13 18:45 UTC, chmnata commented on dags/weather_pull.py
> +        poke_interval=3600,
@gabrielwol pointed out that the timesensor (no async) needs to be poked to figure out if its at target time yet, so we can't get rid of poke_interval :okfine::okfine::okfine:

2024-06-13 18:46 UTC, chmnata approved these changes
:okfine:

2024-06-13 18:47 UTC, merged